export const darkTheme = {
    body: '#151419',
    primary: '#20202C',
    text: '#fff',
    text2: '#fff',
    isDark: true,
    orangeBg: '#FF6D00',
    orangeText: '#FFE4C2',
    greenBg: '#06B16E',
    greenText: '#B4FDD1',
    purpleBg: '#9A48F1',
    purpleText: '#E9D4FF',
    themeColortext: '#fff',
    dotColor:'#565EEF',
    buttonExit: '#fff',
    PopExitBlockColor: '#000',
    PopExitTtlH2:'#fff',
}

export const lightTheme = {
    body: '#EAEEF6',
    primary: '#FFF',
    text: '#000',
    text2: '#565EEF',
    isDark: false,
    orangeBg: '#FFE4C2',
    orangeText: '#FF6D00',
    greenBg: '#B4FDD1',
    greenText: '#06B16E',
    purpleBg: '#E9D4FF',
    purpleText: '#9A48F1',
    themeColortext: '#000',
    dotColor:'#94A6BE',
    buttonExit: '#565EEF',
    PopExitBlockColor: '#FFFFFF',
    PopExitTtlH2:'#000',
}       